### ISSUE TITLE
Bower .bash

### ISSUE THREAD

**Issue by bbrochier** [c2is/c2is-onetea#1]
## .bash file pour init le projet
- on met latest sur les vendors dans le bower.json
- le bash devrait permettre de remplacer latest par la version genere par l'intiateur du projet
- ce permet que lorsque les prochaine personne font un bower install ils ont la mm version que l'initiateur
- l'initiateur lui a bien les latest au moment ou il install le truc

**Comment by devlint** [comment]
Et la description alors ?

**Comment by bbrochier** [comment]
moved to #14
