### ISSUE TITLE
Dossier images

### ISSUE THREAD

**Issue by bbrochier** [c2is/c2is-onetea#15]
quels sous-dossier on met en place.
Initialement
- common
- dyn

Est-ce vraiment standard/comprehensible améliorable?

**Comment by devlint** [comment]
On peut dans `/images/` segmenter directement en dossier en fonction des usages (comme dans `/common/` qu'on supprime), et ajouter un dossier `/placeholder/` (correspond à `/dyn/`) ?

**Comment by bbrochier** [comment]
oui j'aime bien l'idée; et `placeholder` est bien parlant.

Cependant, cela demande une rigueur dans les specs, pour indiquer les images administrables ou non pour pas qu'une images static qu'on croit dynamique se retrouve dans `placeholder`.

D'où peut être l'intérêt d'utiliser des images placeholder plutôt que des découpes de maquettes car on voit direct les images dynamique... mais on s'éloigne alors un peu plus des conditions du site. a voir...

**EDIT:** `tmp` pourrait être parlant aussi (notamment pour les dev) et moins long a taper...

**Comment by bbrochier** [comment]
A voir aussi quels sont les autres dossiers "génériques" qu'on pourrait intégrer par defaut

**Comment by devlint** [comment]
Fainéant :)
donc on aurait une arbo. de ce type ?
- /images
  - /tmp
    - /pageName
    - /moduleName
  - /pageName
  - /moduleName
  - /svg
  - /favicons

**Comment by bbrochier** [comment]
yes, avec un niveau en plus comme pour les less et html?
- /images
  - /tmp
    - /pages
      - /pageName
    - /module
      - /moduleName
  - /pages
    - /pageName
  - /module
    - /moduleName
  - /svg
  - /favicons

**Comment by devlint** [comment]
Qui peut le moins, peut le plus... restons simple et au besoin du projet on
rentrera dans les détails.

**Comment by bbrochier** [comment]
ok, en effet, et je viens de comprendre `pageName` = `pageHome` et non juste `home` pour les dissocier des modules

**Comment by bbrochier** [comment]
structure mise en place
